name: CI Checks

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  lint-android:
    if: github.event.pull_request.draft == false
    name: Lint Android
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Java environment
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Set up Android environment
        uses: android-actions/setup-android@v3

      - name: Lint Android source
        uses: gradle/gradle-build-action@v3
        with:
          arguments: lintDebug

  lint-kotlin:
    if: github.event.pull_request.draft == false
    name: Lint Kotlin
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Java environment
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Lint Kotlin code
        uses: gradle/gradle-build-action@v3
        with:
          arguments: lintKotlin

  unit-tests:
    if: github.event.pull_request.draft == false
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Java environment
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Set up Android environment
        uses: android-actions/setup-android@v3

      - name: Run unit tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: testDebugUnitTest
